### PR TITLE
CI/infrastructure house keeping

### PR DESCRIPTION
**Pull request by jhoblitt**
General infrastructure update and changes needed to keep travis builds working until this module is compatible with puppet 4.0.

### CODE REVIEW

**Comment by antoineco** [comment]
Thanks Johsua! I didn't realize the tests were failing on Puppet 4.0. I'm gonna fix that.

**Comment by antoineco** [comment]
Apparently you already submitted a push request for the compatibility with Puppet 4, which I just merged (#4). I think we shouldn't allow failures for PUPPET_GEM_VERSION="~> 4.0" in 8e56246

**Comment by jhoblitt** [comment]
I'll update the PR is just a moment.

**Comment by jhoblitt** [comment]
The matrix has been updated as requested and I've rebased on master.

**Comment by antoineco** [comment]
Awesome \o/
I merge it and push it to the forge :+1:

**Comment by jhoblitt** [comment]
Rebased again since #5 was just merged. :)

**Comment by jhoblitt** [comment]
Fantastic.  Thank you have and enjoy the rest of the weekend!

**Pull request merged**
